package install

import "os"

// Uninstall deletes the files generated by Install
// It returns the list of files that have been actually deleted
func Uninstall(basePath string) (map[string]InstallationCandidate, error) {
	candidateFiles, err := FindCandidateFiles(basePath)
	if err != nil {
		return candidateFiles, err
	}

	for i, v := range candidateFiles {
		err := os.Remove(v.Path)
		if err != nil {
			if os.IsNotExist(err) {
				delete(candidateFiles, i)
				continue
			}
			return candidateFiles, err
		}
	}

	return candidateFiles, err
}
